"""add bag_details table

Revision ID: 2ece2152f423
Revises: 
Create Date: 2025-11-12 15:36:11.950221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ece2152f423'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bag_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('packaging_name', sa.String(length=30), nullable=True),
    sa.Column('total_bags', sa.Integer(), nullable=True),
    sa.Column('returned_bags', sa.Integer(), nullable=True),
    sa.Column('bags_status', sa.Enum('ACTIVE', 'RETURNED', name='bagsstatus'), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction_mill_operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bag_details_bags_status'), 'bag_details', ['bags_status'], unique=False)
    op.create_index(op.f('ix_bag_details_id'), 'bag_details', ['id'], unique=False)
    op.create_index(op.f('ix_bag_details_packaging_name'), 'bag_details', ['packaging_name'], unique=False)
    op.create_index(op.f('ix_bag_details_returned_bags'), 'bag_details', ['returned_bags'], unique=False)
    op.create_index(op.f('ix_bag_details_total_bags'), 'bag_details', ['total_bags'], unique=False)
    op.create_index(op.f('ix_bag_details_transaction_id'), 'bag_details', ['transaction_id'], unique=False)
    # op.alter_column('broker_details_operations', 'broker_name',
    #            existing_type=sa.TEXT(length=30),
    #            type_=sa.String(length=30),
    #            existing_nullable=True)
    # op.alter_column('broker_details_operations', 'broker_mob_no',
    #            existing_type=sa.TEXT(length=10),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)
    # op.alter_column('broker_details_operations', 'remarks',
    #            existing_type=sa.TEXT(length=50),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_broker_details_operations_brokerage_rate'), 'broker_details_operations', ['brokerage_rate'], unique=False)
    # op.alter_column('godown_details_operations', 'godown_name',
    #            existing_type=sa.TEXT(length=30),
    #            type_=sa.String(length=30),
    #            existing_nullable=True)
    # op.alter_column('godown_details_operations', 'remarks',
    #            existing_type=sa.TEXT(length=50),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # op.alter_column('packaging_details_operations', 'packaging_name',
    #            existing_type=sa.TEXT(length=30),
    #            type_=sa.String(length=30),
    #            existing_nullable=True)
    # op.alter_column('packaging_details_operations', 'packaging_unit',
    #            existing_type=sa.TEXT(length=4),
    #            type_=sa.String(length=4),
    #            existing_nullable=True)
    # op.alter_column('packaging_details_operations', 'remarks',
    #            existing_type=sa.TEXT(length=50),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    # op.create_index(op.f('ix_packaging_details_operations_packaging_unit'), 'packaging_details_operations', ['packaging_unit'], unique=False)
    # op.alter_column('stock_ledger', 'id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    # op.create_index(op.f('ix_stock_ledger_godown_id'), 'stock_ledger', ['godown_id'], unique=False)
    # op.create_index(op.f('ix_stock_ledger_id'), 'stock_ledger', ['id'], unique=False)
    # op.create_index(op.f('ix_stock_ledger_stock_item_id'), 'stock_ledger', ['stock_item_id'], unique=False)
    # op.alter_column('transaction_mill_operations', 'rst_number',
    #            existing_type=sa.TEXT(length=20),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    # op.alter_column('transaction_mill_operations', 'bill_number',
    #            existing_type=sa.TEXT(length=20),
    #            type_=sa.String(length=20),
    #            existing_nullable=True)
    # op.alter_column('transaction_mill_operations', 'vehicle_number',
    #            existing_type=sa.TEXT(length=10),
    #            type_=sa.String(length=10),
    #            existing_nullable=True)
    # op.alter_column('transaction_mill_operations', 'remarks',
    #            existing_type=sa.TEXT(length=50),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    op.create_index(op.f('ix_transaction_mill_operations_transaction_type'), 'transaction_mill_operations', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_mill_operations_transaction_type'), table_name='transaction_mill_operations')
    op.alter_column('transaction_mill_operations', 'remarks',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
    op.alter_column('transaction_mill_operations', 'vehicle_number',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
    op.alter_column('transaction_mill_operations', 'bill_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)
    op.alter_column('transaction_mill_operations', 'rst_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_stock_ledger_stock_item_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_godown_id'), table_name='stock_ledger')
    op.alter_column('stock_ledger', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_packaging_details_operations_packaging_unit'), table_name='packaging_details_operations')
    op.alter_column('packaging_details_operations', 'remarks',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
    op.alter_column('packaging_details_operations', 'packaging_unit',
               existing_type=sa.String(length=4),
               type_=sa.TEXT(length=4),
               existing_nullable=True)
    op.alter_column('packaging_details_operations', 'packaging_name',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(length=30),
               existing_nullable=True)
    op.alter_column('godown_details_operations', 'remarks',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
    op.alter_column('godown_details_operations', 'godown_name',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_broker_details_operations_brokerage_rate'), table_name='broker_details_operations')
    op.alter_column('broker_details_operations', 'remarks',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(length=50),
               existing_nullable=True)
    op.alter_column('broker_details_operations', 'broker_mob_no',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(length=10),
               existing_nullable=True)
    op.alter_column('broker_details_operations', 'broker_name',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(length=30),
               existing_nullable=True)
    op.drop_index(op.f('ix_bag_details_transaction_id'), table_name='bag_details')
    op.drop_index(op.f('ix_bag_details_total_bags'), table_name='bag_details')
    op.drop_index(op.f('ix_bag_details_returned_bags'), table_name='bag_details')
    op.drop_index(op.f('ix_bag_details_packaging_name'), table_name='bag_details')
    op.drop_index(op.f('ix_bag_details_id'), table_name='bag_details')
    op.drop_index(op.f('ix_bag_details_bags_status'), table_name='bag_details')
    op.drop_table('bag_details')
    # ### end Alembic commands ###
