"""added new column 'remaining_bags' in bag_details table

Revision ID: a5b1bd9ffbf9
Revises: 2ece2152f423
Create Date: 2025-11-18 13:44:37.939693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b1bd9ffbf9'
down_revision: Union[str, Sequence[str], None] = '2ece2152f423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bag_details', sa.Column('remaining_bags', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bag_details', 'remaining_bags')
    # ### end Alembic commands ###
